// ui/src/components/IncidentEvidence.vue
<script setup lang="ts">
defineProps<{ evidence: Array<{ title: string; content: string; score?: number; uri?: string }> }>()
</script>

<template>
  <div class="space-y-3">
    <div v-for="(e,i) in evidence" :key="i" class="border rounded-xl p-3">
      <div class="flex items-start justify-between gap-3">
        <div>
          <div class="font-semibold">{{ e.title }}</div>
          <div class="text-xs text-gray-500" v-if="e.score !== undefined">score: {{ e.score.toFixed(3) }}</div>
        </div>
        <a v-if="e.uri" :href="e.uri" target="_blank" class="text-sm underline">Open</a>
      </div>
      <pre class="mt-2 text-sm whitespace-pre-wrap">{{ e.content }}</pre>
    </div>
  </div>
</template>

// ui/src/components/IncidentEvidence.tsx
import React from 'react';

type Evidence = { title: string; content: string; score?: number; uri?: string };

export default function IncidentEvidence({ evidence }: { evidence: Evidence[] }) {
  if (!evidence || evidence.length === 0) return <div>No evidence yet.</div>;

  return (
    <div className="space-y-3">
      {evidence.map((e, i) => (
        <div key={i} style={{border:'1px solid #e5e7eb', borderRadius:12, padding:12}}>
          <div style={{display:'flex', justifyContent:'space-between', gap:8}}>
            <div>
              <div style={{fontWeight:600}}>{e.title}</div>
              {typeof e.score === 'number' && (
                <div style={{fontSize:12, color:'#6b7280'}}>score: {e.score.toFixed(3)}</div>
              )}
            </div>
            {e.uri && (
              <a href={e.uri} target="_blank" rel="noreferrer" style={{fontSize:14, textDecoration:'underline'}}>
                Open
              </a>
            )}
          </div>
          <pre style={{marginTop:8, whiteSpace:'pre-wrap', fontSize:14}}>{e.content}</pre>
        </div>
      ))}
    </div>
  );
}
